### ISSUE TITLE
unable to authenticate with MLS Live for 2017 season

### ISSUE THREAD

**Issue by ralyodio** [micahg/plugin.video.mlslive#3]

**Comment by micahg** [comment]
Hi,

I'm aware. Thanks.

The new apps are not out yet, so I cannot reverse engineer the API just yet.

**Comment by ralyodio** [comment]
first live game is right now, did they release any app yet?

**Comment by micahg** [comment]
Yeah, I have live games working on the BAM_2017 branch. If you want to discuss it head on over to the forum please: http://forum.kodi.tv/showthread.php?tid=158142&page=17
